(function(){
var Pm=function(a,b){return $APP.la[a]=b},rf=function(a,b){var c=Array(a.length-2);$APP.hd(a,0,c,0,2*b);$APP.hd(a,2*(b+1),c,2*b,c.length-2*b);return c},Qm=function(a,b,c){return a.call.apply(a.bind,arguments)},Rm=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},Sm=function(a,b,c){Sm=
Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Qm:Rm;return Sm.apply(null,arguments)},Vm=function(a,b){this.ld=a===Tm&&b||"";this.ad=Um},Wm=function(){if($APP.im instanceof $APP.Pi&&$APP.im.constructor===$APP.Pi&&$APP.im.Zc===$APP.ei)return $APP.im.Wc;$APP.r($APP.im);return"type_error:SafeHtml"},Xm=function(a){var b=new Vm(Tm,$APP.fm instanceof $APP.Kh&&$APP.fm.constructor===$APP.Kh&&$APP.fm.$c===$APP.Jh?$APP.fm.md:"type_error:Const");b instanceof Vm&&b.constructor===
Vm&&b.ad===Um?b=b.ld:($APP.r(b),b="type_error:TrustedResourceUrl");a.src=b.toString()},Ya=function(){},bd=function(a){return null==a?!1:null!=a?a.g&8||$APP.u===a.$b?!0:a.g?!1:$APP.x(Ya,a):$APP.x(Ya,a)},Ym=function(){return function(){function a(b){if(0<arguments.length)for(var c=0,d=Array(arguments.length-0);c<d.length;)d[c]=arguments[c+0],++c;return!1}a.D=0;a.C=function(b){$APP.G(b);return!1};a.m=function(){return!1};return a}()},ag=function(a){a:for(var b=a;;)if(b=$APP.G(b))b=$APP.J(b);else break a;
return a},xe=function(a){return function d(c){return new $APP.S(null,function(){return $APP.Q(c,$APP.v($APP.cd.a?$APP.cd.a(c):$APP.cd.call(null,c))?$APP.re(d,$APP.Pc([$APP.G.a?$APP.G.a(c):$APP.G.call(null,c)])):null)},null,null)}(a)},ye=function(a){return $APP.we(function(b){return!$APP.cd(b)},$APP.I(xe(a)))},ih=function(a,b,c){if($APP.yd(c)){var d=$APP.ce($APP.Ad,$APP.qe.b(a,c));return b.a?b.a(d):b.call(null,d)}return $APP.Se(c)?(d=new $APP.ef(function(){var e=$APP.kb(c);return a.a?a.a(e):a.call(null,
e)}(),function(){var e=$APP.lb(c);return a.a?a.a(e):a.call(null,e)}()),b.a?b.a(d):b.call(null,d)):$APP.jd(c)?(d=ag($APP.qe.b(a,c)),b.a?b.a(d):b.call(null,d)):$APP.ed(c)?(d=$APP.nd(function(e,f){return $APP.Qc.b(e,a.a?a.a(f):a.call(null,f))},c,c),b.a?b.a(d):b.call(null,d)):bd(c)?(d=$APP.ze($APP.Tc(c),$APP.qe.b(a,c)),b.a?b.a(d):b.call(null,d)):b.a?b.a(c):b.call(null,c)},jh=function(a,b){b=$APP.G(b);for(var c=null,d=0,e=0;;)if(e<d){var f=c.F(null,e),h=$APP.R(f,0,null);f=$APP.R(f,1,null);a.addEventListener(h,
f);e+=1}else if(b=$APP.G(b))$APP.gd(b)?(c=$APP.Rb(b),b=$APP.Sb(b),h=c,d=$APP.O(c),c=h):(c=$APP.H(b),h=$APP.R(c,0,null),f=$APP.R(c,1,null),a.addEventListener(h,f),b=$APP.J(b),c=null,d=0),e=0;else return null},lh=function(a){var b=$APP.qj($APP.ie);a=a.a?a.a(b):a.call(null,b);$APP.oe(b,mh.a?mh.a(a):mh.call(null,a));return b},mh=function(a){var b=a.u?a.u():a.call(null);return new $APP.za(null,3,[$APP.Ag,function(){return function e(d){return new $APP.S(null,function(){for(;;){var f=$APP.G(d);if(f){if($APP.gd(f)){var h=
$APP.Rb(f),k=$APP.O(h),l=$APP.Qd(k);a:for(var n=0;;)if(n<k){var m=$APP.B(h,n);m=lh(m);l.add(m);n+=1}else{h=!0;break a}return h?$APP.T($APP.U(l),e($APP.Sb(f))):$APP.T($APP.U(l),null)}l=$APP.H(f);return $APP.Q(lh(l),e($APP.I(f)))}return null}},null,null)}(b.a?b.a($APP.Lg):b.call(null,$APP.Lg))}(),$APP.Fg,b,$APP.vg,a],null)},nh=function(a){var b=oh;ph.a?ph.a(b):ph.call(null,b);return b.appendChild(kh(lh(a)))},qh=function(a,b){var c=null==b?$APP.ie:b;return $APP.ze($APP.ie,$APP.we(function(d){var e=$APP.R(d,
0,null);d=$APP.R(d,1,null);return!$APP.M.b($APP.lc(c.a?c.a(e):c.call(null,e)),$APP.lc(d))},null==a?$APP.ie:a))},rh=function(a,b,c){a:{var d=qh(b.a?b.a($APP.Kg):b.call(null,$APP.Kg),c.a?c.a($APP.Kg):c.call(null,$APP.Kg));d=$APP.G(d);for(var e=null,f=0,h=0;;)if(h<f){var k=e.F(null,h),l=$APP.R(k,0,null);k=$APP.R(k,1,null);a.removeEventListener(l,k);h+=1}else if(d=$APP.G(d))$APP.gd(d)?(e=$APP.Rb(d),d=$APP.Sb(d),l=e,f=$APP.O(e),e=l):(e=$APP.H(d),l=$APP.R(e,0,null),k=$APP.R(e,1,null),a.removeEventListener(l,
k),d=$APP.J(d),e=null,f=0),h=0;else break a}jh(a,qh(c.a?c.a($APP.Kg):c.call(null,$APP.Kg),b.a?b.a($APP.Kg):b.call(null,$APP.Kg)))},sh=function(a,b,c){a:{b=qh(c.a?c.a($APP.ah):c.call(null,$APP.ah),b.a?b.a($APP.Kg):b.call(null,$APP.Kg));b=$APP.G(b);for(var d=null,e=0,f=0;;)if(f<e){var h=d.F(null,f);c=$APP.R(h,0,null);h=$APP.R(h,1,null);a.style[c]=h;f+=1}else if(b=$APP.G(b))$APP.gd(b)?(d=$APP.Rb(b),b=$APP.Sb(b),c=d,e=$APP.O(d),d=c):(d=$APP.H(b),c=$APP.R(d,0,null),h=$APP.R(d,1,null),a.style[c]=h,b=$APP.J(b),
d=null,e=0),f=0;else break a}},uh=function(a){return me(function(b){return $APP.Ac(b)||(null!=b?$APP.u===b.Bb||(b.jc?0:$APP.x($APP.Qa,b)):$APP.x($APP.Qa,b))?"fn":b},Xc.m(a,$APP.ah,$APP.Pc([$APP.Kg])))},vh=function(a,b){return a.parentNode.replaceChild(b,a)},th=function(a,b){var c=b.a?b.a($APP.Fg):b.call(null,$APP.Fg),d=$APP.nb(a),e=d.a?d.a($APP.Fg):d.call(null,$APP.Fg);if($APP.M.b(uh.a?uh.a(c):uh.call(null,c),uh.a?uh.a(e):uh.call(null,e))){rh(b.a?b.a($APP.Qg):b.call(null,$APP.Qg),c,e);sh(b.a?b.a($APP.Qg):
b.call(null,$APP.Qg),c,e);a=$APP.G($APP.qe.f($APP.Ve,b.a?b.a($APP.Ag):b.call(null,$APP.Ag),d.a?d.a($APP.Ag):d.call(null,$APP.Ag)));b=null;for(var f=0,h=0;;)if(h<f){var k=b.F(null,h),l=$APP.R(k,0,null),n=$APP.R(k,1,null);$APP.pe.b(n,function(q,t,w,z,A,C){return function(E){return $APP.Vf.m($APP.Pc([$APP.nb(C),E]))}}(a,b,f,h,k,l,n,c,d,e));th(n,$APP.nb(l));h+=1}else{var m=$APP.G(a);if(m){k=m;if($APP.gd(k))a=$APP.Rb(k),h=$APP.Sb(k),b=a,f=$APP.O(a),a=h;else{var p=$APP.H(k);l=$APP.R(p,0,null);n=$APP.R(p,
1,null);$APP.pe.b(n,function(q,t,w,z,A,C){return function(E){return $APP.Vf.m($APP.Pc([$APP.nb(C),E]))}}(a,b,f,h,p,l,n,k,m,c,d,e));th(n,$APP.nb(l));a=$APP.J(k);b=null;f=0}h=0}else return null}}else return c=b.a?b.a($APP.Qg):b.call(null,$APP.Qg),d=kh(a),vh.b?vh.b(c,d):vh.call(null,c,d)},wh=function(a){var b=$APP.nb(a);$APP.pe.b(a,function(c){return $APP.Vf.m($APP.Pc([c,function(){var d=c.a?c.a($APP.vg):c.call(null,$APP.vg);return mh.a?mh.a(d):mh.call(null,d)}()]))});return th(a,b)},yh=function(){var a=
$APP.qj(new $APP.za(null,1,[Ug,null],null));return function(b){return new $APP.W(null,2,5,$APP.Y,[$APP.nb(a),function(c){$APP.pe.b(a,c);return wh(b)}],null)}},Zm=function(a,b){this.jb=a;this.n=b;this.g=2;this.s=0},$m=function(a){return a.jb.length===a.n},an=function(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)},bn=function(){var a=$APP.aa.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&
window.addEventListener&&!$APP.na("Presto")&&(a=function(){var e=an("IFRAME");e.style.display="none";Xm(e);document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.write(Wm());e.close();var h="callImmediate"+Math.random(),k="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=Sm(function(l){if(("*"==k||l.origin==k)&&l.data==h)this.port1.onmessage()},this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(h,
k)}}});if("undefined"!==typeof a&&!$APP.na("Trident")&&!$APP.na("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.Tc;c.Tc=null;e()}};return function(e){d.next={Tc:e};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in an("SCRIPT")?function(e){var f=an("SCRIPT");f.onreadystatechange=function(){f.onreadystatechange=null;f.parentNode.removeChild(f);f=null;e();e=null};document.documentElement.appendChild(f)}:function(e){$APP.aa.setTimeout(e,
0)}},fn=function(){cn=!0;dn=!1;for(var a=0;;){var b=$APP.Im.pop();if(null!=b&&(b.u?b.u():b.call(null),1024>a)){a+=1;continue}break}cn=!1;return 0<$APP.Im.length?en.u?en.u():en.call(null):null},en=function(){if(dn&&cn)return null;dn=!0;!$APP.Ac($APP.aa.setImmediate)||$APP.aa.Window&&$APP.aa.Window.prototype&&!$APP.na("Edge")&&$APP.aa.Window.prototype.setImmediate==$APP.aa.setImmediate?(gn||(gn=bn()),gn(fn)):$APP.aa.setImmediate(fn)},hn=function(a){$APP.Im.unbounded_unshift(a);en()},mn=function(a){if("undefined"===
typeof $APP.pa||"undefined"===typeof $APP.ta||"undefined"===typeof $APP.ai||"undefined"===typeof jn||"undefined"===typeof kn||"undefined"===typeof ln)ln=function(b,c){this.O=b;this.fd=c;this.g=425984;this.s=0},ln.prototype.N=function(b,c){return new ln(this.O,c)},ln.prototype.H=function(){return this.fd},ln.prototype.nb=function(){return this.O},ln.wb=function(){return new $APP.W(null,2,5,$APP.Y,[$APP.nm,$APP.ym],null)},ln.hb=!0,ln.Sa="cljs.core.async.impl.channels/t_cljs$core$async$impl$channels7826",
ln.qb=function(b){return $APP.Fb(b,"cljs.core.async.impl.channels/t_cljs$core$async$impl$channels7826")};return new ln(a,$APP.ie)},nn=function(a,b){this.Bc=a;this.O=b},pn=function(a){return on(a.Bc)},qn=function(a,b,c,d){this.vc=a;this.Jc=0;this.pc=b;this.Ic=0;this.jb=c;this.closed=!1;this.lc=d},rn=function(a){for(;;){var b=a.pc.pop();if(null!=b){var c=b.Bc;hn(function(d){return function(){return d.a?d.a(!0):d.call(null,!0)}}(c.Rb,c,b.O,b,a))}break}a.pc.cleanup(Ym());a.zc(null)},sn=function(a,b,c){var d=
a.closed;if(d)return mn(!d);if($APP.v(function(){var m=a.jb;return $APP.v(m)?$APP.La($m(a.jb)):m}())){var e=$APP.Cc(a.lc.b?a.lc.b(a.jb,b):a.lc.call(null,a.jb,b));c=function(){for(var m=$APP.Rc;;)if(0<a.vc.length&&0<$APP.O(a.jb)){var p=a.vc.pop(),q=p.Rb,t=a.jb.jb.pop();m=$APP.Qc.b(m,function(w,z,A){return function(){return z.a?z.a(A):z.call(null,A)}}(m,q,t,p,e,d,a))}else return m}();e&&rn(a);if($APP.G(c)){c=$APP.G(c);for(var f=null,h=0,k=0;;)if(k<h){var l=f.F(null,k);hn(l);k+=1}else if(c=$APP.G(c))f=
c,$APP.gd(f)?(c=$APP.Rb(f),k=$APP.Sb(f),f=c,h=$APP.O(c),c=k):(c=$APP.H(f),hn(c),c=$APP.J(f),f=null,h=0),k=0;else break}return mn(!0)}f=function(){for(;;){var m=a.vc.pop();if($APP.v(m)){if($APP.v(!0))return m}else return null}}();if($APP.v(f)){var n=f.Rb;hn(function(){return n.a?n.a(b):n.call(null,b)});return mn(!0)}64<a.Ic?(a.Ic=0,a.pc.cleanup(pn)):a.Ic+=1;$APP.v(c.Hc())&&a.pc.unbounded_unshift(new nn(c,b));return null},un=function(a,b){if(null!=a.jb&&0<$APP.O(a.jb)){b=b.Rb;if($APP.v(b)){var c=a.jb.jb.pop(),
d=$APP.La($m(a.jb))&&0<a.pc.length?function(){for(var w=$APP.Rc;;){var z=a.pc.pop(),A=z.O;z=z.Bc.Rb;w=$APP.v(z)?$APP.Qc.b(w,z):w;A=$APP.v(z)?$APP.Cc(a.lc.b?a.lc.b(a.jb,A):a.lc.call(null,a.jb,A)):null;if(!($APP.La(A)&&$APP.La($m(a.jb))&&0<a.pc.length))return new $APP.W(null,2,5,$APP.Y,[A,w],null)}}():null,e=$APP.R(d,0,null),f=$APP.R(d,1,null);$APP.v(e)&&rn(a);for(var h=$APP.G(f),k=null,l=0,n=0;;)if(n<l){var m=k.F(null,n);hn(function(w,z,A,C,E){return function(){return E.a?E.a(!0):E.call(null,!0)}}(h,
k,l,n,m,c,d,e,f,b,b,a));n+=1}else{var p=$APP.G(h);if(p){m=p;if($APP.gd(m))h=$APP.Rb(m),n=$APP.Sb(m),k=h,l=$APP.O(h),h=n;else{var q=$APP.H(m);hn(function(w,z,A,C,E){return function(){return E.a?E.a(!0):E.call(null,!0)}}(h,k,l,n,q,m,p,c,d,e,f,b,b,a));h=$APP.J(m);k=null;l=0}n=0}else break}return mn(c)}return null}c=function(){for(;;){var w=a.pc.pop();if($APP.v(w)){if(on(w.Bc))return w}else return null}}();if($APP.v(c)){var t=tn(c.Bc);hn(function(){return t.a?t.a(!0):t.call(null,!0)});return mn(c.O)}if($APP.v(a.closed))return $APP.v(a.jb)&&
(a.lc.a?a.lc.a(a.jb):a.lc.call(null,a.jb)),$APP.v($APP.v(!0)?b.Rb:!0)?(b=function(){var w=a.jb;return $APP.v(w)?0<$APP.O(a.jb):w}(),c=$APP.v(b)?a.jb.jb.pop():null,mn(c)):null;64<a.Jc?(a.Jc=0,a.vc.cleanup(on)):a.Jc+=1;$APP.v(b.Hc())&&a.vc.unbounded_unshift(b);return null},vn=function(a){console.log(a);return null},xn=function(a,b){var c=$APP.v(null)?null:vn;b=c.a?c.a(b):c.call(null,b);return null==b?a:wn.b(a,b)},yn=function(a){return new qn(new $APP.kk(Array(32)),new $APP.kk(Array(32)),a,function(){var b=
$APP.v(null)?null.a?null.a(wn):null.call(null,wn):wn;return function(){function c(f,h){try{return b.b?b.b(f,h):b.call(null,f,h)}catch(k){return xn(f,k)}}function d(f){try{return b.a?b.a(f):b.call(null,f)}catch(h){return xn(f,h)}}var e=null;e=function(f,h){switch(arguments.length){case 1:return d.call(this,f);case 2:return c.call(this,f,h)}throw Error("Invalid arity: "+arguments.length);};e.a=d;e.b=c;return e}()}())},Bn=function(a){if("undefined"===typeof $APP.pa||"undefined"===typeof $APP.ta||"undefined"===
typeof $APP.ai||"undefined"===typeof jn||"undefined"===typeof zn||"undefined"===typeof An)An=function(b,c){this.Rb=b;this.jd=c;this.g=393216;this.s=0},An.prototype.N=function(b,c){return new An(this.Rb,c)},An.prototype.H=function(){return this.jd},An.prototype.Pc=function(){return!0},An.prototype.Hc=function(){return!0},An.prototype.Qc=function(){return this.Rb},An.wb=function(){return new $APP.W(null,2,5,$APP.Y,[$APP.Zg,$APP.Bm],null)},An.hb=!0,An.Sa="cljs.core.async.impl.ioc-helpers/t_cljs$core$async$impl$ioc_helpers9395",
An.qb=function(b){return $APP.Fb(b,"cljs.core.async.impl.ioc-helpers/t_cljs$core$async$impl$ioc_helpers9395")};return new An(a,$APP.ie)},Cn=function(a){try{var b=a[0];return b.a?b.a(a):b.call(null,a)}catch(c){if(c instanceof Object)throw b=c,a[6].zc(null),b;throw c;}},Dn=function(a,b,c){c=un(c,Bn(function(d){a[2]=d;a[1]=b;return Cn(a)}));return $APP.v(c)?(a[2]=$APP.nb(c),a[1]=b,$APP.rm):null},En=function(a,b,c,d){c=sn(c,d,Bn(function(e){a[2]=e;a[1]=b;return Cn(a)}));return $APP.v(c)?(a[2]=$APP.nb(c),
a[1]=b,$APP.rm):null},Fn=function(a,b){a=a[6];null!=b&&sn(a,b,Bn(function(){return null}));a.zc(null);return a},Gn=function(a){for(;;){var b=a[4],c=$APP.pm.a(b),d=$APP.Am.a(b),e=a[5];if($APP.v(function(){var f=e;return $APP.v(f)?$APP.La(b):f}()))throw e;if($APP.v(function(){var f=e;return $APP.v(f)?(f=c,$APP.v(f)?$APP.M.b($APP.bk,d)||e instanceof d:f):f}())){a[1]=c;a[2]=e;a[5]=null;a[4]=$APP.Vc.m(b,$APP.pm,null,$APP.Pc([$APP.Am,null]));break}if($APP.v(function(){var f=e;return $APP.v(f)?$APP.La(c)&&
$APP.La($APP.Em.a(b)):f}()))a[4]=$APP.sm.a(b);else{if($APP.v(function(){var f=e;return $APP.v(f)?$APP.La(c)?$APP.Em.a(b):!1:f}())){a[1]=$APP.Em.a(b);a[4]=$APP.Vc.f(b,$APP.Em,null);break}if($APP.v($APP.La(e)?$APP.Em.a(b):!1)){a[1]=$APP.Em.a(b);a[4]=$APP.Vc.f(b,$APP.Em,null);break}if($APP.La(e)&&$APP.La($APP.Em.a(b))){a[1]=$APP.zm.a(b);a[4]=$APP.sm.a(b);break}throw Error("No matching clause");}}},Hn=function(a){a=$APP.M.b(a,0)?null:a;return yn("number"===typeof a?new Zm(new $APP.kk(Array(a)),a):a)},
zh=function(a,b){return null!=a?b.a?b.a(a):b.call(null,a):null},Jn=function(){var a=Hn(null),b=Hn(null),c=new Worker("/chess-cljs/js/worker.js");c.addEventListener("message",function(e){var f=Hn(1);hn(function(){var h=function(){return function(){function l(p){for(;;){a:try{for(;;){var q=p,t=q[1];var w=1===t?En(q,2,b,e.data):2===t?Fn(q,q[2]):null;if(!$APP.mj(w,$APP.rm)){var z=w;break a}}}catch(A){if(A instanceof Object)p[5]=A,Gn(p),z=$APP.rm;else throw A;}if(!$APP.mj(z,$APP.rm))return z}}function n(){var p=
[null,null,null,null,null,null,null];p[0]=m;p[1]=1;return p}var m=null;m=function(p){switch(arguments.length){case 0:return n.call(this);case 1:return l.call(this,p)}throw Error("Invalid arity: "+arguments.length);};m.u=n;m.a=l;return m}()}(),k=function(){var l=h();l[6]=f;return l}();return Cn(k)});return f});var d=Hn(1);hn(function(){var e=function(){function h(k){var l=k[1];if(7===l)return k[2]=k[2],k[1]=4,$APP.rm;if(1===l)return Dn(k,2,a);if(4===l)return Fn(k,k[2]);if(6===l)return k[2]=null,k[1]=
7,$APP.rm;if(3===l){l=k[7];var n=$APP.R(l,0,null);l=$APP.R(l,1,null);var m=$APP.La(null==n);k[9]=l;k[8]=n;k[1]=m?5:6;return $APP.rm}return 2===l?(l=k[2],n=$APP.R(l,0,null),m=$APP.R(l,1,null),k[7]=l,k[10]=n,k[11]=m,k[2]=null,k[1]=3,$APP.rm):9===l?(l=k[9],n=$APP.em(k[2]),En(k,8,l,n)):5===l?(l=k[8],l=$APP.Jj($APP.Pc([l])),l=c.postMessage(l),k[12]=l,Dn(k,9,b)):10===l?(l=k[2],k[7]=l,k[2]=null,k[1]=3,$APP.rm):8===l?(l=k[9],n=k[2],l=In(l),k[13]=n,k[14]=l,Dn(k,10,a)):null}return function(){function k(m){for(;;){a:try{for(;;){var p=
h(m);if(!$APP.mj(p,$APP.rm)){var q=p;break a}}}catch(t){if(t instanceof Object)m[5]=t,Gn(m),q=$APP.rm;else throw t;}if(!$APP.mj(q,$APP.rm))return q}}function l(){var m=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];m[0]=n;m[1]=1;return m}var n=null;n=function(m){switch(arguments.length){case 0:return l.call(this);case 1:return k.call(this,m)}throw Error("Invalid arity: "+arguments.length);};n.u=l;n.a=k;return n}()}(),f=function(){var h=e();h[6]=d;return h}();return Cn(f)});
return a},xh=function(a){var b=null!=(a.a?a.a($APP.Ig):a.call(null,$APP.Ig)),c=new $APP.za(null,4,["float","left","width","15%","background",$APP.v(a.a?a.a(Ug):a.call(null,Ug))?"#40aad4":$APP.v(a.a?a.a(yg):a.call(null,yg))?"#4ae896":$APP.v(a.a?a.a(Og):a.call(null,Og))?"#ada284":"#fff","border",$APP.v(a.a?a.a(yg):a.call(null,yg))?"1px dotted #40aad4":"1px solid #999"],null);return function(){return function(){return $APP.Vc.f(new $APP.za(null,3,[$APP.$g,"div",$APP.ah,c,$APP.Kg,new $APP.za(null,1,["click",
function(){var d=a.a?a.a(Bg):a.call(null,Bg);return d.u?d.u():d.call(null)}],null)],null),$APP.Lg,ye(new $APP.W(null,1,5,$APP.Y,[b?function(){return function(){return $APP.Vc.f(new $APP.za(null,3,[$APP.$g,"image",$APP.ah,new $APP.za(null,1,["width","90%"],null),$APP.Sg,new $APP.za(null,1,["src",["/chess-cljs/pieces/",$APP.y.a(a.a?a.a($APP.Z):a.call(null,$APP.Z)),"_",$APP.y.a(a.a?a.a($APP.Ig):a.call(null,$APP.Ig)),".svg"].join("")],null)],null),$APP.Lg,ye($APP.Rc))}}:$APP.tc],null)))}}},Ch=function(a,
b){var c=$APP.R(b,0,null),d=$APP.R(b,1,null);return $APP.we(function(e){var f=$APP.R(e,0,null);e=$APP.R(e,1,null);return $APP.M.b(f,c)?null==d?!0:$APP.M.b(e,d):!1},a)},Dh=function(a,b,c,d,e,f,h){f=Ch(f,new $APP.W(null,2,5,$APP.Y,[d.a?d.a(Ug):d.call(null,Ug),new $APP.W(null,2,5,$APP.Y,[b,c],null)],null));var k=$APP.R(f,0,null);return $APP.Vc.m(a,Og,$APP.M.b(((c+(b%2+2)%2)%2+2)%2,0),$APP.Pc([Bg,function(){if(null==k){var l=function(n){return $APP.Vc.f(n,Ug,new $APP.W(null,2,5,$APP.Y,[b,c],null))};return e.a?
e.a(l):e.call(null,l)}return h.a?h.a(k):h.call(null,k)},yg,null!=k,Ug,$APP.M.b(new $APP.W(null,2,5,$APP.Y,[b,c],null),d.a?d.a(Ug):d.call(null,Ug)),$APP.Ig,zh(a.a?a.a($APP.Ig):a.call(null,$APP.Ig),function(l){return $APP.Md(l)}),$APP.Z,zh(a.a?a.a($APP.Z):a.call(null,$APP.Z),function(l){return $APP.Md(l)})]))},Eh=function(a){var b=null!=a&&(a.g&64||$APP.u===a.Qa)?$APP.ce($APP.Sf,a):a,c=$APP.oc.b(b,wg),d=$APP.oc.b(b,Xg),e=$APP.oc.b(b,Rg),f=$APP.oc.b(b,Hg),h=.9*function(){var k=window.innerWidth,l=window.innerHeight;
return k<l?k:l}();return function(k){var l=new $APP.W(null,1,5,$APP.Y,[yh()],null);return function(){var n=$APP.qe.b(function(t){return t.a?t.a(k):t.call(null,k)},l),m=$APP.R(n,0,null),p=$APP.R(m,0,null),q=$APP.R(m,1,null);return $APP.Vc.f(new $APP.za(null,2,[$APP.$g,"div",$APP.ah,new $APP.za(null,4,["width",[$APP.y.a(h),"px"].join(""),"height",[$APP.y.a(h),"px"].join(""),"display","inline-block","margin","5px"],null)],null),$APP.Lg,ye(new $APP.W(null,1,5,$APP.Y,[function(){return function z(w){return new $APP.S(null,
function(){for(;;){var A=$APP.G(w);if(A){var C=A;if($APP.gd(C)){var E=$APP.Rb(C),K=$APP.O(E),ca=$APP.Qd(K);return function(){for(var V=0;;)if(V<K){var da=$APP.B(E,V),ra=$APP.R(da,0,null),ja=$APP.R(da,1,null);$APP.Sd(ca,function(qa,Ba,Ta,Ca,Ua,Ga,zb,Va,qb,Ib,Ed,Fd,Gd,Jb,se,Hd,Ub,rb,Id,rc,Kb){return function(){return function(Vb,Lb,te,Wb,eb,ue,Jc,Jd,Xb,Kd,gi,hi,ii,ji,ki,li,mi,ni,oi,pi,qi,ri){return function(){return $APP.Vc.f(new $APP.za(null,2,[$APP.$g,"div",$APP.ah,new $APP.za(null,2,["display","flex",
"height","13%"],null)],null),$APP.Lg,ye(new $APP.W(null,1,5,$APP.Y,[function(){return function(si,ti,ui,vi,wi,xi,yi,zi,Ai,Bi,Ci,Di,Ei,Fi,Gi,Hi,Ii,Ji,Ki,Li,Mi,Ni){return function bh(Oi){return new $APP.S(null,function(Ti,Ui,Vi,Wi,ch,Xi,Yi,Zi,$i,aj,bj,cj,dh,eh,dj,ej,fj,gj,hj,ij,fh,gh){return function(){for(;;){var ld=$APP.G(Oi);if(ld){if($APP.gd(ld)){var Yb=$APP.Rb(ld),hh=$APP.O(Yb),Ld=$APP.Qd(hh);a:for(var tf=0;;)if(tf<hh){var ve=$APP.B(Yb,tf),uf=$APP.R(ve,0,null);ve=$APP.R(ve,1,null);uf=xh(Dh(uf,
ch,ve,dh,eh,fh,gh));Ld.add(uf);tf+=1}else{Yb=!0;break a}return Yb?$APP.T($APP.U(Ld),bh($APP.Sb(ld))):$APP.T($APP.U(Ld),null)}Yb=$APP.H(ld);Ld=$APP.R(Yb,0,null);Yb=$APP.R(Yb,1,null);return $APP.Q(xh(Dh(Ld,ch,Yb,dh,eh,fh,gh)),bh($APP.I(ld)))}return null}}}(si,ti,ui,vi,wi,xi,yi,zi,Ai,Bi,Ci,Di,Ei,Fi,Gi,Hi,Ii,Ji,Ki,Li,Mi,Ni),null,null)}}(Vb,Lb,te,Wb,eb,ue,Jc,Jd,Xb,Kd,gi,hi,ii,ji,ki,li,mi,ni,oi,pi,qi,ri)($APP.Ah($APP.Pc([Wb,$APP.$f(0,8)])))}()],null)))}}(qa,$APP.Rc,Ba,Ta,Ca,Ua,Ga,zb,Va,qb,Ib,Ed,Fd,Gd,Jb,
se,Hd,Ub,rb,Id,rc,Kb)}}(V,da,ra,ja,E,K,ca,C,A,n,m,p,q,l,h,a,b,c,d,e,f));V+=1}else return!0}()?$APP.T($APP.U(ca),z($APP.Sb(C))):$APP.T($APP.U(ca),null)}var X=$APP.H(C),Fa=$APP.R(X,0,null),sa=$APP.R(X,1,null);return $APP.Q(function(V,da,ra,ja,qa,Ba,Ta,Ca,Ua,Ga,zb,Va,qb,Ib,Ed,Fd,Gd){return function(){return function(){return $APP.Vc.f(new $APP.za(null,2,[$APP.$g,"div",$APP.ah,new $APP.za(null,2,["display","flex","height","13%"],null)],null),$APP.Lg,ye(new $APP.W(null,1,5,$APP.Y,[function(){return function Hd(se){return new $APP.S(null,
function(){for(;;){var Ub=$APP.G(se);if(Ub){if($APP.gd(Ub)){var rb=$APP.Rb(Ub),Id=$APP.O(rb),rc=$APP.Qd(Id);a:for(var Kb=0;;)if(Kb<Id){var Vb=$APP.B(rb,Kb),Lb=$APP.R(Vb,0,null);Vb=$APP.R(Vb,1,null);Lb=xh(Dh(Lb,ra,Vb,Ca,Ua,Fd,Gd));rc.add(Lb);Kb+=1}else{rb=!0;break a}return rb?$APP.T($APP.U(rc),Hd($APP.Sb(Ub))):$APP.T($APP.U(rc),null)}rb=$APP.H(Ub);rc=$APP.R(rb,0,null);rb=$APP.R(rb,1,null);return $APP.Q(xh(Dh(rc,ra,rb,Ca,Ua,Fd,Gd)),Hd($APP.I(Ub)))}return null}},null,null)}($APP.Ah($APP.Pc([da,$APP.$f(0,
8)])))}()],null)))}}}(X,Fa,sa,C,A,n,m,p,q,l,h,a,b,c,d,e,f),z($APP.I(C)))}return null}},null,null)}($APP.Ah($APP.Pc([c,$APP.$f(0,8)])))}()],null)))}}},Kn=function(a,b,c){var d=Hn(1);hn(function(){var e=function(){return function(){function h(n){for(;;){a:try{for(;;){var m=void 0,p=void 0,q=n,t=q[1];if(1===t){var w=Hn(10);c:{p=[b,c];for(var z=[$APP.om,$APP.um],A=z.length,C=0,E=$APP.Mb($APP.mf);;)if(C<A){var K=C+1,ca=$APP.Pb(E,z[C],p[C]);C=K;E=ca}else{var X=$APP.Ob(E);break c}}var Fa=new $APP.W(null,
2,5,$APP.Y,[X,w],null);q[7]=w;m=q;var sa=En(m,2,a,Fa)}else 2===t?(p=q[7],q[8]=q[2],m=q,sa=Dn(m,3,p)):sa=3===t?Fn(q,q[2]):null;if(!$APP.mj(sa,$APP.rm)){var V=sa;break a}}}catch(da){if(da instanceof Object)n[5]=da,Gn(n),V=$APP.rm;else throw da;}if(!$APP.mj(V,$APP.rm))return V}}function k(){var n=[null,null,null,null,null,null,null,null,null];n[0]=l;n[1]=1;return n}var l=null;l=function(n){switch(arguments.length){case 0:return k.call(this);case 1:return h.call(this,n)}throw Error("Invalid arity: "+
arguments.length);};l.u=k;l.a=h;return l}()}(),f=function(){var h=e();h[6]=d;return h}();return Cn(f)});return d},Mn=function(){var a=$APP.qj($APP.ug),b=$APP.qj($APP.Ih),c=$APP.qj($APP.Rc),d=$APP.qj(!0);return function(e){if($APP.v($APP.nb(d))){var f=Hn(1);hn(function(){var h=function(){return function(){function l(p){for(;;){a:try{for(;;){var q=p,t=q[1];if(1===t){var w=Ln.sb(null,$APP.Ih,$APP.ug);var z=Dn(q,2,w)}else if(2===t){var A=$APP.oe(c,q[2]),C=$APP.oe(d,!1),E=wh(e);q[7]=A;q[8]=C;z=Fn(q,E)}else z=
null;if(!$APP.mj(z,$APP.rm)){var K=z;break a}}}catch(ca){if(ca instanceof Object)p[5]=ca,Gn(p),K=$APP.rm;else throw ca;}if(!$APP.mj(K,$APP.rm))return K}}function n(){var p=[null,null,null,null,null,null,null,null,null];p[0]=m;p[1]=1;return p}var m=null;m=function(p){switch(arguments.length){case 0:return n.call(this);case 1:return l.call(this,p)}throw Error("Invalid arity: "+arguments.length);};m.u=n;m.a=l;return m}()}(),k=function(){var l=h();l[6]=f;return l}();return Cn(k)})}return new $APP.W(null,
3,5,$APP.Y,[$APP.nb(b),$APP.nb(c),function(h){var k=Hn(1);hn(function(){var l=function(){function m(p){var q=p[1];if(1===q)return q=$APP.nb(b),q=Ln.kb(null,q,h),Dn(p,2,q);if(2===q){q=p[2];var t=$APP.Lh($APP.ug);t=$APP.oe(a,t);var w=$APP.oe(b,q),z=$APP.oe(c,$APP.Rc),A=wh(e),C=$APP.Lh($APP.ug);C=Ln.Ab(null,q,C);p[7]=q;p[8]=t;p[9]=w;p[10]=A;p[11]=z;return Dn(p,4,C)}return 3===q?(q=$APP.oe(b,p[2]),t=$APP.nb(b),t=Ln.sb(null,t,$APP.ug),p[12]=q,Dn(p,5,t)):4===q?(q=p[7],q=Ln.kb(null,q,p[2]),Dn(p,3,q)):5===
q?(q=$APP.oe(c,p[2]),t=$APP.oe(a,$APP.ug),w=wh(e),p[13]=q,p[14]=t,Fn(p,w)):null}return function(){function p(w){for(;;){a:try{for(;;){var z=m(w);if(!$APP.mj(z,$APP.rm)){var A=z;break a}}}catch(C){if(C instanceof Object)w[5]=C,Gn(w),A=$APP.rm;else throw C;}if(!$APP.mj(A,$APP.rm))return A}}function q(){var w=[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null];w[0]=t;w[1]=1;return w}var t=null;t=function(w){switch(arguments.length){case 0:return q.call(this);case 1:return p.call(this,
w)}throw Error("Invalid arity: "+arguments.length);};t.u=q;t.a=p;return t}()}(),n=function(){var m=l();m[6]=k;return m}();return Cn(n)});return k}],null)}},fi=function(){return nh(function(a){var b=new $APP.W(null,1,5,$APP.Y,[Mn()],null);return function(){var c=$APP.qe.b(function(f){return f.a?f.a(a):f.call(null,a)},b),d=$APP.R(c,0,null);c=$APP.R(d,0,null);var e=$APP.R(d,1,null);d=$APP.R(d,2,null);return $APP.Vc.f(new $APP.za(null,2,[$APP.$g,"div",$APP.ah,new $APP.za(null,2,["width","100%","height",
"100%"],null)],null),$APP.Lg,ye(new $APP.W(null,1,5,$APP.Y,[Eh($APP.Pc([wg,c,Xg,$APP.ug,Rg,e,Hg,d]))],null)))}})},Nn=function(){return fi()};$APP.bi.prototype.Qc=Pm(7,function(){return this.Rb});$APP.bi.prototype.Hc=Pm(6,function(){return this.zb});$APP.bi.prototype.Pc=Pm(5,function(){return!0});
$APP.xf.prototype.Za=Pm(4,function(a,b,c){var d=1<<(b>>>a&31);if(0===(this.G&d))return this;var e=$APP.xd(this.G&d-1),f=this.c[2*e],h=this.c[2*e+1];return null==f?(a=h.Za(a+5,b,c),a===h?this:null!=a?new $APP.xf(null,this.G,$APP.qf(this.c,2*e+1,a)):this.G===d?null:new $APP.xf(null,this.G^d,rf(this.c,e))):$APP.pf(c,f)?new $APP.xf(null,this.G^d,rf(this.c,e)):this});
$APP.Bf.prototype.Za=Pm(3,function(a,b,c){var d=b>>>a&31,e=this.c[d];if(null!=e){a=e.Za(a+5,b,c);if(a===e)d=this;else if(null==a)if(8>=this.h)a:{e=this.c;a=e.length;b=Array(2*(this.h-1));c=0;for(var f=1,h=0;;)if(c<a)c!==d&&null!=e[c]?(b[f]=e[c],f+=2,h|=1<<c,c+=1):c+=1;else{d=new $APP.xf(null,h,b);break a}}else d=new $APP.Bf(null,this.h-1,$APP.qf(this.c,d,a));else d=new $APP.Bf(null,this.h,$APP.qf(this.c,d,a));return d}return this});
$APP.Jf.prototype.Za=Pm(2,function(a,b,c){a=$APP.If(this.c,this.h,c);return-1===a?this:1===this.h?null:new $APP.Jf(null,this.qa,this.h-1,rf(this.c,$APP.wd(a)))});$APP.za.prototype.ob=Pm(1,function(a,b){if(0<=$APP.Wc(this.c,b)){a=this.c.length;var c=a-2;if(0===c)return this.T(null);c=Array(c);for(var d=0,e=0;;){if(d>=a)return new $APP.za(this.l,this.h-1,c,null);$APP.M.b(b,this.c[d])?d+=2:(c[e]=this.c[d],c[e+1]=this.c[d+1],e+=2,d+=2)}}else return this});
$APP.Pf.prototype.ob=Pm(0,function(a,b){if(null==b)return this.aa?new $APP.Pf(this.l,this.h-1,this.root,!1,null,null):this;if(null==this.root)return this;a=this.root.Za(0,$APP.lc(b),b);return a===this.root?this:new $APP.Pf(this.l,this.h-1,a,this.aa,this.$,null)});
var Tm={},Um={},jb=function jb(a,b){if(null!=a&&null!=a.ob)return a.ob(a,b);var d=jb[$APP.r(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=jb._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw $APP.Ma("IMap.-dissoc",a);},Xc=function Xc(a){switch(arguments.length){case 1:return Xc.a(arguments[0]);case 2:return Xc.b(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return Xc.m(arguments[0],arguments[1],new $APP.sc(c.slice(2),
0,null))}};Xc.a=function(a){return a};Xc.b=function(a,b){return null==a?null:jb(a,b)};Xc.m=function(a,b,c){for(;;){if(null==a)return null;a=Xc.b(a,b);if($APP.v(c))b=$APP.H(c),c=$APP.J(c);else return a}};Xc.C=function(a){var b=$APP.H(a),c=$APP.J(a);a=$APP.H(c);c=$APP.J(c);return this.m(b,a,c)};Xc.D=2;
var me=function me(a,b){return ih($APP.le(me,a),a,b)},kh=function kh(a){var c=$APP.nb(a),d=Xc.b(c.a?c.a($APP.Fg):c.call(null,$APP.Fg),$APP.Lg),e=document.createElement(d.a?d.a($APP.$g):d.call(null,$APP.$g)),f=new $APP.za(null,8,[$APP.$g,$APP.ud,$APP.Cg,$APP.ud,$APP.zg,function(p){return e.className=p},$APP.Sg,function(p){p=$APP.G(p);for(var q=null,t=0,w=0;;)if(w<t){var z=q.F(null,w),A=$APP.R(z,0,null);z=$APP.R(z,1,null);e[A]=z;w+=1}else if(p=$APP.G(p))$APP.gd(p)?(q=$APP.Rb(p),p=$APP.Sb(p),A=q,t=$APP.O(q),
q=A):(q=$APP.H(p),A=$APP.R(q,0,null),z=$APP.R(q,1,null),e[A]=z,p=$APP.J(p),q=null,t=0),w=0;else return null},$APP.ah,function(p){p=$APP.G(p);for(var q=null,t=0,w=0;;)if(w<t){var z=q.F(null,w),A=$APP.R(z,0,null);z=$APP.R(z,1,null);e.style[A]=z;w+=1}else if(p=$APP.G(p))$APP.gd(p)?(q=$APP.Rb(p),p=$APP.Sb(p),A=q,t=$APP.O(q),q=A):(q=$APP.H(p),A=$APP.R(q,0,null),z=$APP.R(q,1,null),e.style[A]=z,p=$APP.J(p),q=null,t=0),w=0;else return null},$APP.Kg,function(p){return jh(e,p)},$APP.Yg,function(p){return e.href=
p},$APP.tg,function(p){return e.innerHTML=p}],null);d=$APP.G(d);for(var h=null,k=0,l=0;;)if(l<k){var n=h.F(null,l),m=$APP.R(n,0,null);n=$APP.R(n,1,null);m=f.a?f.a(m):f.call(null,m);m.a?m.a(n):m.call(null,n);l+=1}else if(d=$APP.G(d))$APP.gd(d)?(k=$APP.Rb(d),d=$APP.Sb(d),h=k,k=$APP.O(k)):(k=$APP.H(d),h=$APP.R(k,0,null),k=$APP.R(k,1,null),h=f.a?f.a(h):f.call(null,h),h.a?h.a(k):h.call(null,k),d=$APP.J(d),h=null,k=0),l=0;else break;c=$APP.G(c.a?c.a($APP.Ag):c.call(null,$APP.Ag));f=null;for(h=d=0;;)if(h<
d)k=f.F(null,h),e.appendChild(kh.a?kh.a(k):kh.call(null,k)),h+=1;else if(c=$APP.G(c))f=c,$APP.gd(f)?(c=$APP.Rb(f),h=$APP.Sb(f),f=c,d=$APP.O(c),c=h):(c=$APP.H(f),e.appendChild(kh.a?kh.a(c):kh.call(null,c)),c=$APP.J(f),f=null,d=0),h=0;else break;$APP.pe.b(a,function(p){return $APP.Vc.f(p,$APP.Qg,e)});return e},ph=function ph(a){return $APP.v(a.firstChild)?(a.removeChild(a.firstChild),ph.a?ph.a(a):ph.call(null,a)):a},jn={},In=function In(a){if(null!=a&&null!=a.zc)return a.zc(a);var c=In[$APP.r(null==
a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=In._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $APP.Ma("Channel.close!",a);},on=function on(a){if(null!=a&&null!=a.Pc)return!0;var c=on[$APP.r(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=on._;if(null!=c)return c.a?c.a(a):c.call(null,a);throw $APP.Ma("Handler.active?",a);},tn=function tn(a){if(null!=a&&null!=a.Qc)return a.Rb;var c=tn[$APP.r(null==a?null:a)];if(null!=c)return c.a?c.a(a):c.call(null,a);c=tn._;if(null!=
c)return c.a?c.a(a):c.call(null,a);throw $APP.Ma("Handler.commit",a);},On=function On(a,b){if(null!=a&&null!=a.Uc)return a.Uc(a,b);var d=On[$APP.r(null==a?null:a)];if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);d=On._;if(null!=d)return d.b?d.b(a,b):d.call(null,a,b);throw $APP.Ma("Buffer.add!*",a);},wn=function wn(a){switch(arguments.length){case 1:return wn.a(arguments[0]);case 2:return wn.b(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.y.a(arguments.length)].join(""));}};
wn.a=function(a){return a};wn.b=function(a,b){return On(a,b)};wn.D=2;Zm.prototype.Uc=function(a,b){this.jb.unbounded_unshift(b);return this};Zm.prototype.I=function(){return this.jb.length};var gn,cn=!1,dn=!1,kn={},ln;
qn.prototype.zc=function(){var a=this;if(!a.closed)for(a.closed=!0,$APP.v(function(){var e=a.jb;return $APP.v(e)?0===a.pc.length:e}())&&(a.lc.a?a.lc.a(a.jb):a.lc.call(null,a.jb));;){var b=a.vc.pop();if(null!=b){var c=b.Rb,d=$APP.v(function(){var e=a.jb;return $APP.v(e)?0<$APP.O(a.jb):e}())?a.jb.jb.pop():null;hn(function(e,f){return function(){return e.a?e.a(f):e.call(null,f)}}(c,d,b,this))}else break}return null};
var zn={},An,wg=new $APP.F(null,"board","board",-1907017633),yg=new $APP.F(null,"can-move-to","can-move-to",260990653),Bg=new $APP.F(null,"on-click","on-click",1632826543),Pn=new $APP.nc(null,"meta7495","meta7495",-701548147,null),Hg=new $APP.F(null,"on-move","on-move",-1779179710),Og=new $APP.F(null,"tint","tint",-1286736913),Rg=new $APP.F(null,"moves","moves",927465255),Ug=new $APP.F(null,"selected","selected",574897764),Xg=new $APP.F(null,"player","player",-97687400),Qn=new $APP.nc(null,"c","c",
-122660552,null);var Rn={},Sn,Ln=function(){var a=Jn();$APP.og($APP.Pc(["loaded worker, theoretically"]));if("undefined"===typeof $APP.Jm||"undefined"===typeof $APP.Km||"undefined"===typeof Rn||"undefined"===typeof Sn)Sn=function(b,c){this.Fc=b;this.gd=c;this.g=393216;this.s=0},Sn.prototype.N=function(b,c){return new Sn(this.Fc,c)},Sn.prototype.H=function(){return this.gd},Sn.prototype.kb=function(b,c,d){var e=this,f=Hn(1);hn(function(){var h=function(){return function(){function l(p){for(;;){a:try{for(;;){var q=
p,t=q[1];if(1===t){var w=Kn(e.Fc,$APP.Cm,$APP.Pc([c,d]));var z=Dn(q,2,w)}else if(2===t){var A=q[2],C=$APP.og($APP.Pc(["move response: ",A]));q[7]=C;z=Fn(q,A)}else z=null;if(!$APP.mj(z,$APP.rm)){var E=z;break a}}}catch(K){if(K instanceof Object)p[5]=K,Gn(p),E=$APP.rm;else throw K;}if(!$APP.mj(E,$APP.rm))return E}}function n(){var p=[null,null,null,null,null,null,null,null];p[0]=m;p[1]=1;return p}var m=null;m=function(p){switch(arguments.length){case 0:return n.call(this);case 1:return l.call(this,
p)}throw Error("Invalid arity: "+arguments.length);};m.u=n;m.a=l;return m}()}(),k=function(){var l=h();l[6]=f;return l}();return Cn(k)});return f},Sn.prototype.sb=function(b,c,d){var e=this,f=Hn(1);hn(function(){var h=function(){return function(){function l(p){for(;;){a:try{for(;;){var q=p,t=q[1];if(1===t){var w=Kn(e.Fc,$APP.wm,$APP.Pc([c,d]));var z=Dn(q,2,w)}else z=2===t?Fn(q,q[2]):null;if(!$APP.mj(z,$APP.rm)){var A=z;break a}}}catch(C){if(C instanceof Object)p[5]=C,Gn(p),A=$APP.rm;else throw C;
}if(!$APP.mj(A,$APP.rm))return A}}function n(){var p=[null,null,null,null,null,null,null];p[0]=m;p[1]=1;return p}var m=null;m=function(p){switch(arguments.length){case 0:return n.call(this);case 1:return l.call(this,p)}throw Error("Invalid arity: "+arguments.length);};m.u=n;m.a=l;return m}()}(),k=function(){var l=h();l[6]=f;return l}();return Cn(k)});return f},Sn.prototype.Ab=function(b,c,d){var e=this,f=Hn(1);hn(function(){var h=function(){return function(){function l(p){for(;;){a:try{for(;;){var q=
p,t=q[1];if(1===t){var w=Kn(e.Fc,$APP.vm,$APP.Pc([c,d]));var z=Dn(q,2,w)}else if(2===t){var A=q[2];$APP.og($APP.Pc(["printl: ",A]));z=Fn(q,A)}else z=null;if(!$APP.mj(z,$APP.rm)){var C=z;break a}}}catch(E){if(E instanceof Object)p[5]=E,Gn(p),C=$APP.rm;else throw E;}if(!$APP.mj(C,$APP.rm))return C}}function n(){var p=[null,null,null,null,null,null,null];p[0]=m;p[1]=1;return p}var m=null;m=function(p){switch(arguments.length){case 0:return n.call(this);case 1:return l.call(this,p)}throw Error("Invalid arity: "+
arguments.length);};m.u=n;m.a=l;return m}()}(),k=function(){var l=h();l[6]=f;return l}();return Cn(k)});return f},Sn.wb=function(){return new $APP.W(null,2,5,$APP.Y,[Qn,Pn],null)},Sn.hb=!0,Sn.Sa="chess.engine.worker-engine/t_chess$engine$worker_engine7494",Sn.qb=function(b){return $APP.Fb(b,"chess.engine.worker-engine/t_chess$engine$worker_engine7494")};return new Sn(a,$APP.ie)}();var oh=document.getElementById("app"),Tn=["chess","core","init"],Un=$APP.aa;Tn[0]in Un||"undefined"==typeof Un.execScript||Un.execScript("var "+Tn[0]);for(var Vn;Tn.length&&(Vn=Tn.shift());)Tn.length||void 0===Nn?Un=Un[Vn]&&Un[Vn]!==Object.prototype[Vn]?Un[Vn]:Un[Vn]={}:Un[Vn]=Nn;fi();
}).call(this);